export const MAX_PHOTO_SIZE_BYTES = 10 * 1024 * 1024
export const MAX_PHOTO_SIZE_MB = 10

const IMAGE_TYPES = new Set([
  'image/jpeg',
  'image/jpg',
  'image/png',
  'image/gif',
  'image/webp',
  'image/heic',
  'image/heif',
  'image/avif'
])

const IMAGE_EXTENSIONS = /\.(jpe?g|png|gif|webp|heic|heif|avif)$/i

const AUTO_TITLE_PATTERN =
  /^(IMG_|DSC|PXL_|WP_|Screenshot|photo_\d|VID_)/i

export const isAutoGeneratedTitle = (title: string) => {
  const trimmed = title.trim()
  if (!trimmed) return true
  if (AUTO_TITLE_PATTERN.test(trimmed)) return true
  if (/\.(jpe?g|png|gif|webp|heic|heif|avif)$/i.test(trimmed)) return true
  if (/^\d{8}[_-]\d{6}$/.test(trimmed)) return true
  return false
}

export const getDisplayTitle = (title: string) => {
  if (isAutoGeneratedTitle(title)) return null
  return title.trim()
}

export const derivePhotoTitle = (filename: string) => {
  const name = filename.replace(/\.[^/.]+$/, '').trim()
  if (!name || isAutoGeneratedTitle(name)) return 'Untitled'
  return name
}

export const isValidPhotoFile = (file: File) => {
  if (file.type && IMAGE_TYPES.has(file.type.toLowerCase())) {
    return true
  }

  return IMAGE_EXTENSIONS.test(file.name)
}

export const validatePhotoFile = (file: File): string | null => {
  if (!isValidPhotoFile(file)) {
    return `"${file.name}" is not a supported image format`
  }

  if (file.size > MAX_PHOTO_SIZE_BYTES) {
    return `"${file.name}" exceeds ${MAX_PHOTO_SIZE_MB}MB`
  }

  return null
}

export type PhotoUploadOptions = {
  title?: string
  description?: string
  isPublic?: boolean
  capturedAt?: string
}

export const uploadPhoto = async (file: File, options: PhotoUploadOptions = {}) => {
  const formData = new FormData()
  formData.append('file', file)
  const title = options.title?.trim() || derivePhotoTitle(file.name)
  formData.append('title', title)

  if (options.description) {
    formData.append('description', options.description)
  }

  formData.append('isPublic', options.isPublic !== false ? 'true' : 'false')

  if (options.capturedAt) {
    formData.append('capturedAt', options.capturedAt)
  }

  const response = await fetch('/api/photos', {
    method: 'POST',
    body: formData
  })

  if (!response.ok) {
    const error = await response.json().catch(() => ({ error: 'Upload failed' }))
    throw new Error(error.error || 'Upload failed')
  }

  return response.json()
}

export const resolveContentType = (file: File) => {
  if (file.type) {
    return file.type
  }

  const extension = file.name.split('.').pop()?.toLowerCase()

  switch (extension) {
    case 'jpg':
    case 'jpeg':
      return 'image/jpeg'
    case 'png':
      return 'image/png'
    case 'gif':
      return 'image/gif'
    case 'webp':
      return 'image/webp'
    case 'heic':
      return 'image/heic'
    case 'heif':
      return 'image/heif'
    case 'avif':
      return 'image/avif'
    default:
      return 'application/octet-stream'
  }
}
